// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenancyServer.Samples.AspNetIdentityAndEFCore.Data;

namespace MultiTenancyServer.Samples.AspNetIdentityAndEFCore.Data.Management.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    partial class ManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("MultiTenancyServer.Samples.AspNetIdentityAndEFCore.Models.ApplicationTenant", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CanonicalName")
                        .HasMaxLength(256);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(256);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedCanonicalName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCanonicalName")
                        .IsUnique()
                        .HasName("CanonicalNameIndex");

                    b.ToTable("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
